USE QLDETAI
GO

--Q1
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE PHAI = N'NỮ'


--Q2
SELECT GV.HOTEN, GV.LUONG AS LUONG_TRUOC, GV.LUONG * 1.1 AS LUONG_SAU 
FROM GIAOVIEN GV


--Q3
SELECT DISTINCT GV.MAGV
--FROM GIAOVIEN GV , BOMON BM ON GV.MABM = BM.MABM
FROM GIAOVIEN GV, BOMON BM
WHERE GV.HOTEN LIKE N'NGUYỄN %' AND GV.LUONG > 2000 OR (BM.TRUONGBM = GV.MAGV AND YEAR (BM.NGAYNHANCHUC) > 1995) 


--Q4
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin'


--Q5
SELECT *
FROM BOMON BM LEFT JOIN GIAOVIEN GV ON BM.TRUONGBM = GV.MAGV
WHERE BM.TRUONGBM = GV.MAGV
