USE QLDETAI
GO

--Q1
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE PHAI = N'NỮ'

--Q2
SELECT GV.HOTEN, GV.LUONG AS LUONG_TRUOC, GV.LUONG * 1.1 AS LUONG_SAU 
FROM GIAOVIEN GV

--Q3
SELECT DISTINCT GV.MAGV
--FROM GIAOVIEN GV , BOMON BM ON GV.MABM = BM.MABM
FROM GIAOVIEN GV, BOMON BM
WHERE GV.HOTEN LIKE N'NGUYỄN %' AND GV.LUONG > 2000 OR (BM.TRUONGBM = GV.MAGV AND YEAR (BM.NGAYNHANCHUC) > 1995) 

--Q4
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin'

--Q5
SELECT *
FROM BOMON BM LEFT JOIN GIAOVIEN GV ON BM.TRUONGBM = GV.MAGV
WHERE BM.TRUONGBM = GV.MAGV

--Q6
SELECT *
FROM GIAOVIEN GV LEFT JOIN BOMON BM ON BM.MABM = GV.MABM

--Q7
SELECT DT.TENDT, GV.HOTEN
FROM DETAI DT JOIN GIAOVIEN GV ON GV.MAGV = DT.GVCNDT

--Q8
SELECT *
FROM KHOA K JOIN GIAOVIEN GV ON K.TRUONGKHOA = GV.MAGV

--Q9
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MADT = '006' AND TG.MAGV = GV.MAGV
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'VI SINH'

--Q10
SELECT DT.MADT, CD.*, HOTEN, NGSINH, DIACHI
FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
WHERE DT.CAPQL = N'Thành phố'

--Q11
SELECT GV.HOTEN AS HOTEN_TUNG_GV, QLCM.HOTEN AS HOTEN_GVQLCM
FROM GIAOVIEN GV JOIN GIAOVIEN QLCM ON GV.GVQLCM = QLCM.MAGV

--Q12
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN GIAOVIEN QLCM ON GV.GVQLCM = QLCM.MAGV
WHERE QLCM.HOTEN = N'NGUYỄN THANH TÙNG'

--Q13
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
WHERE BM.TENBM = N'HỆ THỐNG THÔNG TIN'

--Q14
SELECT DISTINCT GV.HOTEN, CD.TENCD
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE CD.TENCD = N'QUẢN LÝ GIÁO DỤC'

--Q15
SELECT CV.MADT, CV.TENCV, CV.NGAYBD
FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
WHERE DT.TENDT = N'HTTT QUẢN LÝ CÁC TRƯỜNG ĐH' AND DATEDIFF(M, CV.NGAYBD, '3/1/2008') = 0

--Q16
SELECT GV.HOTEN AS HOTEN_TUNG_GV, QLCM.HOTEN AS HOTEN_GVQLCM
FROM GIAOVIEN GV JOIN GIAOVIEN QLCM ON GV.GVQLCM = QLCM.MAGV

--Q17
SELECT *
FROM CONGVIEC
WHERE NGAYBD BETWEEN '01/01/2007' AND '08/01/2007'

--Q18
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN GIAOVIEN TTH ON GV.MABM = TTH.MABM
WHERE TTH.HOTEN = N'TRẦN TRÀ HƯƠNG' AND NOT (GV.HOTEN = TTH.HOTEN)

--Q19
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
JOIN DETAI DT ON DT.GVCNDT = GV.MAGV

--Q20
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA

--Q21
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
JOIN DETAI DT ON DT.GVCNDT = GV.MAGV

--Q22
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA

--Q23
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE GV.MABM = 'HTTT' OR TG.MADT = '001'

--Q24
SELECT GV.HOTEN, GV.MABM
FROM GIAOVIEN GV JOIN GIAOVIEN GV002 ON GV.MABM = GV002.MABM
WHERE GV002.MAGV = '002' AND NOT (GV002.MAGV = GV.MAGV)

--Q25
SELECT GV.*
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM

--Q26
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV


--LAB 4
--Q27
SELECT COUNT(*) AS SO_LUONG_GV, SUM(GV.LUONG) AS TONG_LUONG
FROM GIAOVIEN GV

--Q28
SELECT BM.MABM, BM.TENBM, COUNT(*) AS SO_LUONG_GV, AVG(GV.LUONG) AS LUONG_TB
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
GROUP BY BM.MABM, BM.TENBM

--Q29
SELECT CD.MACD, CD.TENCD, COUNT(*) AS SO_LUONG_DT
FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
GROUP BY CD.MACD, CD.TENCD

--Q30
SELECT GV.MAGV, GV.HOTEN, COUNT(DISTINCT TG.MADT) AS DT_TG
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN

--Q31
SELECT GV.MAGV, GV.HOTEN, COUNT(DISTINCT DT.MADT) AS DT_CN
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.MAGV, GV.HOTEN

--Q32
SELECT GV.MAGV, GV.HOTEN, COUNT(NT.TEN) AS SO_NGUOI_THAN
FROM GIAOVIEN GV JOIN NGUOITHAN NT ON GV.MAGV = NT.MAGV
GROUP BY GV.MAGV, GV.HOTEN

--Q33
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT (TG.MADT) >= 3

--Q34
SELECT COUNT(DISTINCT TG.MAGV) AS SO_GV_TGDT_HHX
FROM THAMGIADT TG JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.TENDT = N'Ứng dụng hoá học xanh'